{% set name = "vtk-m" %}
{% set version = "2.2.0" %}
{% set build = "2" %}
{% set sha256 = "ee66b6bbd33f6ad6f2350e11a7c9328492e53935ba8f66b4b1d01f074eb96341" %}
{% set soversion = version.split('.')[0] + "." + version.split('.')[1] %}
{% set platform_dependent_flags = "" %}
{% set platform_dependent_flags = " -DVTKm_ENABLE_OPENMP=ON" %}  # [unix]
{% set common_flags = "-DCMAKE_BUILD_TYPE=Release -DVTKm_ENABLE_HDF5_IO=ON -DVTKm_ENABLE_EXAMPLES=ON -DVTKm_INSTALL_EXAMPLES=OFF" + platform_dependent_flags %}
{% set vtkm_modules = [
       'cont',
       'filter_clean_grid',
       'filter_connected_components',
       'filter_contour',
       'filter_core',
       'filter_density_estimate',
       'filter_entity_extraction',
       'filter_field_conversion',
       'filter_field_transform',
       'filter_flow',
       'filter_geometry_refinement',
       'filter_image_processing',
       'filter_mesh_info',
       'filter_multi_block',
       'filter_resampling',
       'filter_scalar_topology',
       'filter_vector_analysis',
       'filter_zfp',
       'io',
       'rendering',
       'source',
       'worklet',
] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.kitware.com/vtk/vtk-m/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - cmake -GNinja -S $SRC_DIR  -B build -DCMAKE_INSTALL_PREFIX=$PREFIX {{ common_flags }}  # [unix]
    - cmake -GNinja -S %SRC_DIR% -B build -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% {{ common_flags }}  # [win]
    - cmake --build build -j
    - cmake --install build
    - VTKm_DIR=$PREFIX cmake -GNinja -S $SRC_DIR/examples/smoke_test/ -B smoke_test_build  # [unix]
    - cmake --build smoke_test_build  # [unix]
    - ./smoke_test_build/smoke_test  # [unix]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.23
    - gnuconfig
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - ninja
    - pkg-config
  host:
    - hdf5

test:
  commands:
    {% for module in vtkm_modules %}
    - test -f $PREFIX/lib/libvtkm_{{ module }}-{{ soversion }}.so.{{ version }}  # [linux]
    - test -f $PREFIX/lib/libvtkm_{{ module }}-{{ soversion }}.{{ version }}.dylib  # [osx]
    - if not exist %LIBRARY_PREFIX%\bin\vtkm_{{ module }}-{{ soversion }}.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\vtkm_{{ module }}-{{ soversion }}.lib exit 1  # [win]
    {% endfor %}
    - if not exist %LIBRARY_PREFIX%\include\vtkm-{{ soversion }} exit 1  # [win]

about:
  home: https://m.vtk.org/
  summary: 'Visualization ToolKit for Many-cores (vtk-m)'
  description: |
    VTK-m is a toolkit of scientific visualization algorithms for emerging
    processor architectures. VTK-m supports the fine-grained concurrency for
    data analysis and visualization algorithms required to drive extreme scale
    computing by providing abstract models for data and execution that can be
    applied to a variety of algorithms across many different processor
    architectures.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - vtkm/thirdparty/diy/vtkmdiy/LICENSE.txt
    - vtkm/thirdparty/lcl/vtkmlcl/LICENSE.md
    - vtkm/thirdparty/lodepng/vtkmlodepng/LICENSE
  doc_url: https://docs-m.vtk.org/latest/
  dev_url: https://gitlab.kitware.com/vtk/vtk-m

extra:
  feedstock-name: vtk-m
  recipe-maintainers:
    - vicentebolea
