github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
github_actions:
  self_hosted: true
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
